# The whole thing, start to finish, without anyone driving it.
#
#   fetch the footage -> certify it -> survey every chart -> author what the gate allows ->
#   commit each repair -> refresh the chart videos that are out of date -> write the report
#
# Each stage is resumable and skips what is already done, so this can be killed and restarted
# at any point and will pick up where it stopped. Nothing here makes a judgement call: the gate
# in batch_repair decides what ships, and everything it refuses is written down with a reason.
#
#   python -X utf8 tools/run_corpus.py <video-map.json> [--skip-download] [--no-commit]
#
# Progress goes to work/<tag>-run.log; the answer goes to work/<tag>-report.json and, at the
# end, sources/.
import json
import os
import subprocess
import sys
import time
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY = r"C:\Users\jonec\repos\piu-annotate\.venv\Scripts\python.exe"

def say(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)

def stage(name, args, timeout=None):
    say(f"=== {name}")
    t0 = time.time()
    p = subprocess.run([PY, "-X", "utf8"] + args, cwd=ROOT, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", timeout=timeout)
    tail = [l for l in (p.stdout or "").splitlines() if l.strip()][-12:]
    for l in tail:
        print("    " + l, flush=True)
    say(f"--- {name} done in {time.time() - t0:.0f}s (exit {p.returncode})")
    return p

def main():
    vmap = sys.argv[1]
    tag = os.path.basename(vmap).replace("-video-map.json", "")
    say(f"corpus run over {vmap}")

    if "--skip-download" not in sys.argv:
        # yt-dlp keeps its own archive, so this only fetches what is missing
        stage("fetch footage", [os.path.join("tools", "download_videos.py"), "--map", vmap])

    have = {f.rsplit(".", 1)[0] for f in os.listdir(os.path.join(ROOT, "videos"))
            if not f.startswith(".")}
    want = {e["vid"] for e in json.load(open(os.path.join(ROOT, vmap), encoding="utf-8"))}
    say(f"footage: {len(want & have)} of {len(want)} videos present")

    # certification happens inside the survey (ledger-cached), then the gate runs on every chart
    stage("survey", [os.path.join("tools", "batch_repair.py"), vmap, "--survey"])
    args = [os.path.join("tools", "batch_repair.py"), vmap, "--author", "--no-certify"]
    if "--no-commit" not in sys.argv:
        args.append("--commit")
    stage("author + commit", args)

    report = os.path.join(ROOT, "work", f"{tag}-report.json")
    rows = json.load(open(report, encoding="utf-8")) if os.path.exists(report) else []
    verdicts = Counter(r["verdict"] for r in rows)
    say(f"verdicts: {dict(verdicts)}")
    shipped = [r for r in rows if r.get("authored")]
    if shipped:
        say("repaired:")
        for r in shipped:
            say(f"    {r['chart']}  taps {r.get('final_taps')} + ticks {r.get('final_ticks')} "
                f"= {r['target']}  {r.get('commit', '')}")

    # anything the run proved is stuck on old footage feeds the video refresh, so the two
    # deliverables stay in step with each other
    say("=== the run is finished; what it produced:")
    say(f"    {report}")
    say("    sources/footage-needed-*.json and the Downloads SQL are regenerated by")
    say("    tools/video_refresh_sql.py once this report is folded in")
    say(f"    parked reasons: {dict(Counter(r['reason'].split(' - ')[0][:44] for r in rows if r['verdict'] == 'PARK'))}")

if __name__ == "__main__":
    main()
