# Turns the freshness report into the two things the owner acts on:
#
#   1. a guarded SQL script that repoints every chart whose banked video is older footage than
#      what exists, and sets Side from the new video (a split-screen singles video only);
#   2. the list of charts nobody has shot at the current mix, which is his to record.
#
# Every UPDATE carries the old VideoUrl in its WHERE, so the script is idempotent, cannot
# clobber a video changed by hand since the report, and re-running it is a no-op.
#
#   python -X utf8 tools/video_refresh_sql.py <freshness.json> <catalog.txt> <out.sql> <needs.json>
#                                             [--oembed <cache.json>] [--pilot <pilot.json>]
import json
import os
import re
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EMBED = "https://www.youtube.com/embed/"
CHANNEL = "네브시스터NEVSISTER"

def arg(name, default=None):
    return sys.argv[sys.argv.index(name) + 1] if name in sys.argv else default

def sql_str(s):
    return "N'" + s.replace("'", "''") + "'"

def main():
    fresh_path, cat_path, sql_path, needs_path = sys.argv[1:5]
    doc = json.load(open(fresh_path, encoding="utf-8"))
    rows = [r for r in doc["charts"] if r["action"] == "upgrade"]
    by_id = {r["chartId"]: r for r in doc["charts"]}
    alive = json.load(open(arg("--oembed"), encoding="utf-8")) if arg("--oembed") else {}
    if alive:
        before = len(rows)
        rows = [r for r in rows if alive.get(r["best_vid"], {}).get("ok")]
        print(f"dropped {before - len(rows)} rows whose target video is not reachable")

    lines = [
        "-- Chart video refresh - generated by tools/video_refresh_sql.py",
        f"-- Source: {doc['walk']} ({doc['counts']['titles']} titled uploads), matched to the catalog",
        "-- by song name + the chart code at that video's own mix level, then kept only where the",
        "-- banked video is provably OLDER footage than what the channel has since posted.",
        "--",
        f"-- {len(rows)} charts over {len({r['best_vid'] for r in rows})} videos:",
    ]
    for k, v in Counter(f'{r["banked_era"]} -> {r["best_era"]}' for r in rows).most_common():
        lines.append(f"--   {k:<24} {v}")
    lines += [
        "--",
        "-- Side is taken from the new video: Left/Right when it is a split-screen SINGLES pair",
        "-- (lower level plays on the left), NULL when the chart has the video to itself.",
        "-- Every statement is guarded on the video it is replacing, so this is safe to re-run",
        "-- and will not overwrite anything changed by hand since it was generated.",
        "--",
        "-- Run it, then Clear Cache.",
        "",
        "SET NOCOUNT ON;",
        "DECLARE @changed int = 0, @sides int = 0;",
        "",
    ]
    for r in sorted(rows, key=lambda r: r["chart"]):
        side = sql_str(r["best_side"]) if r["best_side"] else "NULL"
        lines += [
            f"-- {r['chart']}  ({r['banked_era']} -> {r['best_era']})",
            "UPDATE scores.ChartVideo",
            f"   SET VideoUrl = '{EMBED}{r['best_vid']}',",
            f"       ChannelName = {sql_str(CHANNEL)},",
            f"       Side = {side},",
            "       LastUpdated = SYSDATETIMEOFFSET()",
            f" WHERE ChartId = '{r['chartId']}'",
            f"   AND VideoUrl = '{EMBED}{r['banked_vid']}';",
            "SET @changed += @@ROWCOUNT;",
            "",
        ]
    # A split-screen video carries two charts, and only one of them may be moving - the other
    # is often already banked on it with no Side at all. Leaving that half unlabelled would put
    # the pair in two different states, so its Side is corrected in the same script.
    moving = {r["chartId"] for r in rows}
    partners = []
    for r in rows:
        if not r["best_side"]:
            continue
        for other in doc["charts"]:
            if (other["best_vid"] == r["best_vid"] and other["chartId"] not in moving
                    and other["best_side"] and other["banked_vid"] == r["best_vid"]
                    and (other["banked_side"] or "") != other["best_side"]):
                partners.append(other)
    seen = set()
    partners = [p for p in partners if not (p["chartId"] in seen or seen.add(p["chartId"]))]
    if partners:
        lines += ["-- The other half of a split screen this script just moved a chart onto:",
                  "-- same video, side never set.", ""]
        for r in sorted(partners, key=lambda r: r["chart"]):
            lines += [
                f"-- {r['chart']}  (side only)",
                "UPDATE scores.ChartVideo",
                f"   SET Side = {sql_str(r['best_side'])},",
                "       LastUpdated = SYSDATETIMEOFFSET()",
                f" WHERE ChartId = '{r['chartId']}'",
                f"   AND VideoUrl = '{EMBED}{r['best_vid']}'",
                f"   AND (Side IS NULL OR Side <> {sql_str(r['best_side'])});",
                "SET @sides += @@ROWCOUNT;",
                "",
            ]
    lines += [
        f"PRINT CONCAT('chart videos repointed: ', @changed, ' of {len(rows)}');",
        f"PRINT CONCAT('sides corrected on the other half: ', @sides, ' of {len(partners)}');",
        "-- Anything short of the full count is a row whose video already differs from the one",
        "-- this script expected to replace - look at it rather than forcing it.",
        "",
    ]
    with open(sql_path, "w", encoding="utf-8-sig") as fh:
        fh.write("\n".join(lines))
    print(f"{len(rows)} video updates + {len(partners)} side corrections -> {sql_path}")

    # ---- what nobody has shot at the current mix: his to record
    p1, p2, name = {}, {}, {}
    for line in open(cat_path, encoding="utf-8"):
        p = line.rstrip("\n").split("|")
        if len(p) != 8:
            continue
        cid = p[5].upper()
        if p[4] == "Phoenix" and p[3]:
            p1[cid] = int(p[3])
            name[cid] = f"{p[0]} {p[1][0]}{p[2]}"
        if p[4] == "Phoenix2" and p[3]:
            p2[cid] = int(p[3])
    needs = []
    for cid in sorted({c for c in p1 if c in p2 and p1[c] != p2[c]}, key=lambda c: name[c]):
        best = by_id.get(cid, {})
        if best.get("best_era") == "PHOENIX 2":
            continue
        needs.append(dict(chartId=cid, chart=name[cid], why="note count changed Phoenix 1 -> Phoenix 2",
                          p1_notes=p1[cid], p2_notes=p2[cid], delta=p2[cid] - p1[cid],
                          newest_footage=best.get("best_era") or "none matched"))
    if arg("--pilot"):
        pilot = json.load(open(arg("--pilot"), encoding="utf-8"))
        smap = {o["chart"]: o for o in json.load(open(os.path.join(ROOT, "work", "ssc-map-tail.json"),
                                                     encoding="utf-8"))}
        for c in pilot["older_revision"]:
            cid = (smap.get(c["chart"], {}).get("chartId") or "").upper()
            best = by_id.get(cid, {})
            if best.get("action") == "upgrade":
                continue                       # the script above already gives this one newer footage
            needs.append(dict(chartId=cid, chart=c["chart"],
                              why="the footage and our stepfile agree with each other, not the catalog "
                                  "- the file is an older revision and the video is old-era too",
                              footage_judged=c["footage"], file_implied=c["file"], catalog=c["catalog"],
                              newest_footage=best.get("best_era") or "none matched"))
    json.dump(dict(generated=doc["generated"], source="tools/video_refresh_sql.py",
                   note="charts nobody has posted current-mix footage for. Everything else that "
                        "needed newer footage is in the SQL script alongside this file.",
                   counts=dict(total=len(needs), by_reason=dict(Counter(n["why"][:44] for n in needs))),
                   charts=needs), open(needs_path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{len(needs)} charts need a recording -> {needs_path}")

if __name__ == "__main__":
    main()
